CREATE TABLE form_submissions (
  id SERIAL PRIMARY KEY,
  physician VARCHAR(20) NOT NULL,
  first_name VARCHAR(20) NOT NULL,
  middle_name VARCHAR(20),
  last_name VARCHAR(20) NOT NULL,
  suffix VARCHAR(10),
  mobile_number VARCHAR(15) NOT NULL,
  email VARCHAR(50) NOT NULL,
  address_line_1 TEXT NOT NULL,
  city VARCHAR(50) NOT NULL,
  state VARCHAR(50) NOT NULL,
  country VARCHAR(50) NOT NULL,
  insurance_company VARCHAR(50) NOT NULL,
  insurance_member_id VARCHAR(50) NOT NULL,
  effective_date_of_insurance DATE,
  preferred_contact_method VARCHAR(50) NOT NULL,
  referring_provider VARCHAR(50) NOT NULL,
  maiden_name VARCHAR(50),
  date_of_birth DATE NOT NULL,
  birth_time TIME,
  city_of_birth VARCHAR(20) NOT NULL,
  state_of_birth VARCHAR(20) NOT NULL,
  country_of_birth VARCHAR(20) NOT NULL,
  have_siblings BOOLEAN,
  ssn_number VARCHAR(15),
  sex VARCHAR(10) NOT NULL,
  sexual_orientation VARCHAR(50) NOT NULL,
  ethnicity VARCHAR(50),
  affiliated_tribe VARCHAR(50),
  enrolled_as_tribe_member BOOLEAN,
  marital_status VARCHAR(20),
  salutation VARCHAR(20),
  employer VARCHAR(50),
  preferred_language VARCHAR(50),
  preferred_clinic VARCHAR(50),
  status VARCHAR(20),
  test_patient BOOLEAN DEFAULT FALSE
);
